sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectKey=sudhanshugupta-dev_git-rules
sonar.organization=sudhanshugupta-dev
sonar.projectName=git-rules
sonar.sources=.
sonar.sourceEncoding=UTF-8
