name: Validate PR Checklist
on:
    pull_request:
        branches:
            - development
        types: [opened, reopened, synchronize, ready_for_review]

jobs:
    validate-checklist:
        runs-on: ubuntu-latest

        steps:
            - name: Read PR Body
              id: pr_body
              uses: actions/github-script@v7
              with:
                  script: |
                      const body = context.payload.pull_request.body || "";
                      return { body };
