name: eslint_check

on:
  pull_request:
    branches:
      - development
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  lint_check:
    name: eslint_check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npx eslint . --max-warnings=0
