name: Expo EAS Build (Android)

on:
  pull_request:
    branches:
      - development
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  build-android:
    runs-on: ubuntu-latest
    environment: gitrules

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install --global eas-cli
          npm install

      - name: Log in to Expo with Token
        run: eas whoami || eas login --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android (APK)
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: dist/
