name: PR Checks (Branch Name + Prettier + Lint + Test)

on:
  pull_request:
    branches:
      - development
    types: [opened, reopened, synchronize, ready_for_review]



    
jobs:
  validate:
    name: Validate Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier check
        run: npx prettier --check .

      - name: Run ESLint check
        run: npx eslint . --max-warnings=0
