name: PR Checks

on:
  pull_request:
    branches:
      - development
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  branch_check:
    uses: ./.github/workflows/branch_validation.yml

  prettier_check:
    needs: branch_check
    uses: ./.github/workflows/pret_tier.yml

  eslint_check:
    needs: prettier_check
    uses: ./.github/workflows/es_lint.yml

  test_check:
    needs: eslint_check
    uses: ./.github/workflows/jest_test.yml
